name: Deploy Infrastructure

on:
  workflow_dispatch:

env:
  BASE_NAME: aca-shared-001
  LOCATION: uksouth

jobs:
  deploy-ca-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: Set variables
        id: set-vars
        run: | 
          echo "RESOURCE_GROUP_NAME=rg-${{ env.BASE_NAME }}" >> $GITHUB_OUTPUT
          echo "DEPLOYMENT_NAME=${{ env.BASE_NAME }}-deployment-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Create Resource Group
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az group create --name ${{ steps.set-vars.outputs.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}   

      - name: Deploy Bicep
        uses: Azure/cli@v1
        with:
          inlineScript: |
            set -e
            az config set bicep.use_binary_from_path=false
            az bicep install
            az deployment group create --name ${{ steps.set-vars.outputs.DEPLOYMENT_NAME }} --resource-group ${{ steps.set-vars.outputs.RESOURCE_GROUP_NAME }} --template-file ./src/arm/main.bicep --parameters location=${{ env.LOCATION }} --query properties.outputs.result.value -o json | jq -r . > ./src/arm/outputs.json
